baseurl = "http://productmelon.com/"
languageCode = "en-us"
title = "Product Melon"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Steve Dufresne - Product Melon"
	description = "I'm a Product Manager with ideas that I have no time to chase down. I don't want to take them to the grave. Have them internet."

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = "UA-69804458-1"


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Hey, **I'm Steve Dufresne**,<div> Product Melon at <a href='http://www.rebel.com'>Rebel.com</a></div><div>I have ideas.</div>"
		# The icons will be shown if you enter your username
		github = "StevenDufresne"


	[params.about]
		title = "A couple of these ideas are good."
		content = "I'm a Product Manager with ideas that I have no time to chase down. I don't want to take them to the grave. Have them internet."


	[params.portfolio]
		title = "Some ideas"

		[[params.portfolio.gallery1]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Shopping Cart Checkouts"
			description = "The shopping cart should act as a self checkout vehicle. I should be able to connect to the grocery store wifi and pay for the groceries in my cart. Add a simple scanner to the cart. All I would need to do is scan the items as i put them into the cart and walk to my car when I'm done."

		[[params.portfolio.gallery1]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Sanitary Wear"
			description = "I don't know if I'm alone in this, but when the flu season comes around and I'm in public, I have a hard time mentally dealing with the fact that every bar on the bus or door handle on the way to work may have nasty weekend ruining viruses. What I really want is a piece of jewellery that sanitizes my hand after it recognizes that I have touched a disease spreading surface. Consider a ring and a door handle. Can we not have a ring that recognizes pressure from a handle that leaks out hand sanitizer?"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery2]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Nexus 6P - Clean Touch"
			description = "The fingerprint scanner on my Nexus 6P is awesome. It's fast, friendly and easy to find. To make this phone out of this world, it would be awesome if there was a section on the back of the phone that allowed me to interact with the screen. If I want to scroll down, I simply need to move my pointer finger downwards. No more dirty fingers on the screen. <br /><br />More, you could develop a simple algorithm that detects what the next logical action from the user will be within the window. If I move down slightly, the interface could highlight elements that are likely my next action. Answer the question, what do I intend to do?"

		[[params.portfolio.gallery2]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Relative Volume"
			description = "The reality is that my music comes from a multitude of sources. They are not equalized. Volume should be relative to the song. You could profile the song and play the equivalent of '8' for the song. The less I have to touch the volume control, the happier I am."



	[params.contact]
		title = "Get In Touch"
		content = "Have an idea you want to riff on? Send me a message we can have a skype beer and talk product."
		address = [
			"Ottawa, Canada"
		]

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "steve@productmelon.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "What say you?"
			submit = "Send message"